version: "3.1"
services:
  drupal:
    build: .
    image: custom-drupal
    ports:
      - 8080:80
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-themes:/var/www/html/themes
      - drupal-sites:/var/www/html/sites
  database:
    image: mariadb:latest
    restart: always
    volumes:
      - drupal-data:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=drupal
      - MARIADB_USER=maria
      - MARIADB_PASSWORD=example
      - MARIADB_ROOT_PASSWORD=root-pwd

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-themes:
  drupal-sites:
  drupal-data:
